
[recipes]
	#Determines if the BioForge recipes need to be unlocked to be able to craft them
	doBioForgeRecipeProgression = false

[trades]
	#Determines if villagers will sell biomancy items
	addTradesToVillagers = true
	#Determines if wandering traders will sell biomancy items
	addTradesToWanderingTrader = true

[flesh-growth]
	#Determines how much primal energy the Cradle can supply to nearby malignant flesh veins
	#Allowed Values: NONE, LIMITED, UNLIMITED
	primalEnergySupplyOfCradle = "UNLIMITED"

[pehkui-integration]

	[pehkui-integration.enlargement-serum]
		#Maximum scale a mob/player can reach. A value of 2.0 doubles the size of the mob/player.
		#Range: 0.01 ~ 100.0
		maxScale = 2.0
		#How much to add to the scale on each injection.
		#Range: 0.01 ~ 100.0
		scaleStep = 0.25

	[pehkui-integration.shrinking-serum]
		#Minimum scale a mob/player can reach. A value of 0.5 half's the size of the mob/player.
		#Range: 0.01 ~ 100.0
		minScale = 0.25
		#How much to subtract from the scale on each injection.
		#Range: 0.01 ~ 100.0
		scaleStep = 0.25

